site_name: pytorch2keras documentation
theme: readthedocs

pages:
- Home: index.md
- Installation: installation.md
- Getting started: getting_started.md
- Supported layers and models: supported_layers_and_models.md
- API: api.md
- Known problems: known_problems.md
- License: license.md